name: Build and Release
on:
  push:
    branches: [ main, master ]  # Trigger on any push to main or master branch
  workflow_dispatch:  # Allow manual triggering

# Add this permissions block
permissions:
  contents: write
  packages: write
  
jobs:
  build:
    runs-on: windows-latest  # Using Windows runner for .NET build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Using .NET 8.0 as seen in your config
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Windows x64
      run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
      
    - name: Build Linux x64
      run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
      
    - name: Zip Windows build
      run: |
        $publishPath = "src/Gml.Launcher/bin/Release/net8.0/win-x64/publish"
        
        # List files to verify the path before zipping
        Write-Host "Files in publish directory:"
        Get-ChildItem -Path $publishPath -Recurse | ForEach-Object { Write-Host $_.FullName }
        
        Compress-Archive -Path "$publishPath/*" -DestinationPath BebraLand-Launcher-win-x64.zip -Force
      shell: pwsh
      
    - name: Zip Linux build
      run: |
        $publishPath = "src/Gml.Launcher/bin/Release/net8.0/linux-x64/publish"
        
        # List files to verify the path before zipping
        Write-Host "Files in publish directory:"
        Get-ChildItem -Path $publishPath -Recurse | ForEach-Object { Write-Host $_.FullName }
        
        Compress-Archive -Path "$publishPath/*" -DestinationPath BebraLand-Launcher-linux-x64.zip -Force
      shell: pwsh
      
    - name: Generate release tag
      id: tag
      # Update to use environment files instead of set-output
      run: |
        echo "release_tag=build_$(date +'%Y.%m.%d_%H.%M.%S')" >> $GITHUB_ENV
      shell: bash
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.release_tag }}
        name: Automatic build ${{ env.release_tag }}
        files: |
          BebraLand-Launcher-win-x64.zip
          BebraLand-Launcher-linux-x64.zip
        draft: false
        prerelease: false
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
