name: Build and Release
on:
  push:
    branches: [ main, master ]  # Trigger on any push to main or master branch
  workflow_dispatch:  # Allow manual triggering

permissions:
  contents: write
  packages: write
  
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Install .NET workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload install maui-windows
          dotnet workload update
        
      - name: Build Windows x64
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        
      - name: Build Windows x86
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r win-x86 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        continue-on-error: true
      
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=build_$(Get-Date -Format 'yyyy.MM.dd_HH.mm.ss')" >> $env:GITHUB_OUTPUT
        shell: pwsh
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: windows_${{ steps.tag.outputs.release_tag }}
          name: Windows build ${{ steps.tag.outputs.release_tag }}
          files: |
            src/Gml.Launcher/bin/Release/net8.0/win-x64/publish/BebraLand Launcher.exe
            src/Gml.Launcher/bin/Release/net8.0/win-x86/publish/BebraLand Launcher.exe
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Install .NET workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload update
        
      - name: Build OSX x64
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r osx-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        
      - name: Build OSX ARM64
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r osx-arm64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=build_$(date +'%Y.%m.%d_%H.%M.%S')" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: macos_${{ steps.tag.outputs.release_tag }}
          name: MacOS build ${{ steps.tag.outputs.release_tag }}
          files: |
            src/Gml.Launcher/bin/Release/net8.0/osx-x64/publish/BebraLand Launcher
            src/Gml.Launcher/bin/Release/net8.0/osx-arm64/publish/BebraLand Launcher
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
          
      - name: Restore dependencies
        run: dotnet restore

      - name: Install .NET workloads
        run: |
          dotnet workload install wasm-tools
          dotnet workload update
        
      - name: Build Linux x64
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        
      - name: Build Linux ARM64
        run: dotnet publish src/Gml.Launcher/Gml.Launcher.csproj -c Release -r linux-arm64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true /p:EnableCompressionInSingleFile=true /p:UseAppHost=true
        continue-on-error: true
        
      - name: Generate release tag
        id: tag
        run: |
          echo "release_tag=build_$(date +'%Y.%m.%d_%H.%M.%S')" >> $GITHUB_OUTPUT
        shell: bash
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: linux_${{ steps.tag.outputs.release_tag }}
          name: Linux build ${{ steps.tag.outputs.release_tag }}
          files: |
            src/Gml.Launcher/bin/Release/net8.0/linux-x64/publish/BebraLand Launcher
            src/Gml.Launcher/bin/Release/net8.0/linux-arm64/publish/BebraLand Launcher
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
