name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Trigger on tag push with pattern v*, e.g., v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build:
    runs-on: windows-latest  # Using Windows runner for .NET build
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'  # Using .NET 8.0 as seen in your config
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Windows x64
      run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Build Linux x64
      run: dotnet publish -c Release -r linux-x64 --self-contained true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true
      
    - name: Zip Windows build
      run: |
        Compress-Archive -Path bin/Release/net8.0/win-x64/publish/* -DestinationPath GmiLauncher-win-x64.zip
      shell: pwsh
      
    - name: Zip Linux build
      run: |
        Compress-Archive -Path bin/Release/net8.0/linux-x64/publish/* -DestinationPath GmiLauncher-linux-x64.zip
      shell: pwsh
      
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          GmiLauncher-win-x64.zip
          GmiLauncher-linux-x64.zip
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
