name: Build and Publish to GitHub Releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]
        include:
          - runtime: win-x64
            platform: Windows
          - runtime: linux-x64
            platform: Linux
          - runtime: osx-x64
            platform: macOS

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore -c Release

    - name: Publish the project
      run: |
        dotnet publish -c Release \
          -r ${{ matrix.runtime }} \
          --self-contained true \
          --single-file true \
          --ready-to-run true \
          --include-native-libraries true \
          /p:PublishTrimmed=true

    - name: Upload BebraLand Launcher.exe to GitHub Releases
      if: success()
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          $(System.DefaultWorkingDirectory)/src/Gml.Launcher/bin/Release/net8.0/${{ matrix.runtime }}/publish/BebraLand Launcher.exe
        tag: ${{ github.ref }}
        name: Gml.Launcher-${{ matrix.platform }}

    - name: Run tests (optional)
      run: dotnet test --no-build --verbosity normal
