name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Checkout submodules
      run: git submodule update --init --recursive

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Publish
      run: |
        dotnet publish -c Release \
          -r win-x64 \  # Change this for other platforms (e.g., linux-x64, osx-x64)
          --self-contained true \
          --single-file true \
          --ready-to-run true \
          --include-native-libraries true \
          /p:PublishTrimmed=true \
          /p:PublishSingleFile=true

    - name: Test
      run: dotnet test --no-build --verbosity normal
